name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Organisation-Data-Service-Fhir-Api-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }} 
    short_service_name: ${{ variables.short_service_name }} 
    service_base_path: ${{ variables.service_base_path }}
    proxy_path: ''
    apigee_deployments:
      - environment: internal-dev
      - environment: internal-dev-sandbox
      - environment: internal-qa
      - environment: internal-qa-sandbox
      - environment: ref
        depends_on:
          - internal_qa
          - internal_qa_sandbox
      - environment: sandbox
      - environment: int
        depends_on:
          - internal_qa
          - internal_qa_sandbox
