# This is an OpenAPI Specification (https://swagger.io/specification/)
# for organisation-data-service-fhir-api owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'organisation-data-service-fhir-api'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  contact:
    name: 'ODS FHIR API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
  description: |
  
    <div class="nhsd-m-emphasis-box nhsd-m-emphasis-box--emphasis nhsd-!t-margin-bottom-6" aria-label="Highlighted Information">
        <div class="nhsd-a-box nhsd-a-box--border-blue">
            <div class="nhsd-m-emphasis-box__image-box">
                <figure class="nhsd-a-image">
                    <picture class="nhsd-a-image__picture">
                        <img src="//nhs-prod.global.ssl.fastly.net/svg-magic/binaries/content/gallery/icons/info.svg?colour=231f20" alt="" style="object-fit:fill">
                    </picture>
                </figure>
            </div>
            <div class="nhsd-m-emphasis-box__content-box">
            <p class="nhsd-t-heading-s nhsd-t-word-break" id="emphasis-emphasis-30709f1f" data-uipath="website.contentblock.emphasis.heading">Rate limits</p>
                <div data-uipath="website.contentblock.emphasis.content" class="nhsd-t-word-break"><p class="nhsd-t-body">This API is not designed for high volume usage - to ensure a good level of service you should aim to keep usage below 5 requests per second. For more details, see <a href="https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#rate-limits">rate limits</a>. We are working on increasing the capacity of the API. If you have an exceptional need for higher throughput, <a href="https://digital.nhs.uk/developer/help-and-support">contact us</a> to discuss your options.</p></div>            
            </div>
        </div>
    </div> 
  
    ## Overview
    Use this API to access a reduced dataset of health and social care organisations in England and Wales, such as trusts or GP practices, using the [Organisation Data Service (ODS)](https://digital.nhs.uk/services/organisation-data-service). This FHIR API contains a reduced dataset, most useful for transactions. To access the full ODS dataset, including data about succession (history) or relationships, use the [ODS ORD API](http://https://digital.nhs.uk/developer/api-catalogue/organisation-data-service-ord).
    
    You can search for information about an organisation using one or more of their:
    - ODS code
    - last updated date
    - name
    - active or inactive status
    - postcode or city
    - orgnisation's role or primary role, such as [trusts or GP practices](https://developer.nhs.uk/apis/ods/restfulapis_identification_organization.html#tokenods-org-role)
    
    You can also limit the number of results returned, or just request a count of the number of search results.
    
    You cannot:
    - access the full dataset from ODS, specifically no information about succession (history) or relationships
    - search for an organisation using an address
    
    An ODS code is a unique identification code for an organisation that interacts with any area of the NHS. For a full list of the organisation types available, see [CSV downloads](https://digital.nhs.uk/services/organisation-data-service/export-data-files/csv-downloads).
    This API returns the following reduced dataset of an organisation, when searched with an ODS code:
    
    - organisation - ODS code, name, open date, close date, last change date and status if active or inactive
    - address - house or flat number, line 1, line 2, line 3, town, postcode and country
    - contacts - email, website, telephone and fax
    - roles - primary and non-primary roles
   
    For more details, see the [Introduction to FHIR® ODS Lookup API](https://developer.nhs.uk/apis/ods/index.html).
    To access the full ODS dataset, use the [ODS ORD API](https://digital.nhs.uk/developer/api-catalogue/organisation-data-service-ord).
    
    <section class="nhsd-m-emphasis-box nhsd-m-emphasis-box--important nhsd-!t-margin-bottom-6" aria-label="Important Information">
        <div class="nhsd-a-box nhsd-a-box--border-yellow">
                <div class="nhsd-m-emphasis-box__image-box">
                    <figure class="nhsd-a-image">
                        <picture class="nhsd-a-image__picture">
                            <img src="//nhs-prod.global.ssl.fastly.net/svg-magic/binaries/content/gallery/icons/book-open.svg?colour=231f20" alt="" style="object-fit:fill" />
                        </picture>
                    </figure>
                </div>
            <div class="nhsd-m-emphasis-box__content-box">
                    <div data-uipath="website.contentblock.emphasis.content" class="nhsd-t-word-break"><p class="nhsd-t-body">For a non-technical overview of how to build software that deals with organisations and healthcare services, see <a href="https://digital.nhs.uk/developer/guides-and-documentation/building-healthcare-software/organisations-and-services">Building healthcare software - organisations and healthcare services</a>.</p></div>
            </div>
        </div>
    </section>
    
    ## Who can use this API
    This API can only be used to support the delivery of health and social care.
    
    ## Related APIs
    The following API also gives access to the Organisation Data Service:
    - [ODS Organisation Reference Data (ORD) API](https://digital.nhs.uk/developer/api-catalogue/organisation-data-service-ord) - use this API to access the full ODS dataset
    
    The following API is also related to this API:
    - [Spine Directory Service - FHIR API](https://digital.nhs.uk/developer/api-catalogue/spine-directory-service-fhir) - use this API to access ASID information and messaging endpoint details in the Spine Directory Service (SDS).
    
    ## API status and roadmap
    This API is [in production](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses).
    To see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/?order=popular&filter=allexceptdone&tag=ods-api#controls).
    If you have any other queries, [contact us](https://digital.nhs.uk/developer/help-and-support).
    
    ## Service level
    This API is a bronze service, meaning it is operational and supported only during business hours (8am to 6pm), Monday to Friday excluding bank holidays.
    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).
    
    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest).
    
    It also conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#fhir) global standard for health care data exchange. Specifically, it is based on the HL7 FHIR STU3 Messaging Implementation.
    
    You do not need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules. In particular:
    - resource names are capitalised, singular and in American English, for example`/Organization` not `/organisations`
    - array names are singular, for example `line` not `lines` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object
    
    There are [libraries and SDKs available](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) to help with FHIR API integration.
    
    ## Network access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).
    
    ## Security and authorisation
    This API is [open-access](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#open-access-apis), which means:
    - we do not authenticate or authorise the calling application
    - we do not authenticate or authorise the end user - they might not even be present
    
    We generally use open-access APIs for public data, where security is not a concern. Our open-access APIs are generally RESTful APIs. For more details on how to access them, see our [open-access REST API tutorial](https://https://digital.nhs.uk/developer/guides-and-documentation/tutorials/open-access-rest-api-tutorial).
    
    ## Environments and testing
    
    | Environments                | Base URLs                                                              |
    | -----------------           | ---------------------------------------------------------------------- |
    | User acceptance test (UAT)  |`https://uat.directory.spineservices.nhs.uk/STU3/`                      |
    | Production                  |`https://directory.spineservices.nhs.uk/STU3/`                          |
    
    For example:
    'https://uat.directory.spineservices.nhs.uk/STU3/Organization/RJY'
    returns the reduced dataset for the organisation whose ODS code is RJY.
    
    ## Onboarding
    This API is open-access, and there is no onboarding process or assurance required.
    
    ## Errors
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:
    - 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    - 400 to 499 if it failed because of a client error by your application
    - 500 to 599 if it failed because of an error on our server


servers:
  - url: 'https://sandbox.api.service.nhs.uk/organisation-data-service-fhir-api'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/organisation-data-service-fhir-api'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/organisation-data-service-fhir-api'
    description: Production environment.   
    
paths:
  /Organization:
    get:
      summary: Get a single organization for the specified id (ODS code).
      
      operationId: get-single-organisation-id
      description: |
        Given a specified id (ODS code), get a single orgainsation. 
        
      parameters:
        - in: header
          name: X-Correlation-ID
          required: false
          description: |
            An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters.
            Mirrored back in a response header.
          schema:
            type: string
            example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
        - in: query
          name: _id
          description: |
            The logical id of the resource (ODS Code)
            Expressed as `<type>|<value>` where `<type>` must be `https://fhir.nhs.uk/Id/nhs-number` and `<value>` must be a [valid NHS number](https://www.datadictionary.nhs.uk/attributes/nhs_number.html).
          required: true
          schema:
            type: string
            example: 'TBC'
        - in: query
          name: _lastUpdated
          description: To select resources based on the last time they were changed.
          required: false
          schema:
            type: string
            example: 'gt2017-04-01'
        - in: query
          name: identifier
          description: The identifier for the organisation (ODS Code).
          required: false
          schema:
            type: string
            example: 'AF1234'
        - in: query
          name: name
          description: A portion of the organisation's name.
          required: false
          schema:
            type: string
            example: 'Derby Teaching Hospitals NHS Foundation Trust'
        - in: query
          name: active
          description: Whether the organisation's record is still in active use
          required: false
          schema:
            type: string
            example: 'true'
        - in: query
          name: address-postalcode
          description: A postcode specified in an address
          required: false
          schema:
            type: string
            example: 'DE22 3NE'
        - in: query
          name: address-city
          description: A city specified in an address
          required: false
          schema:
            type: string
            example: 'derby'    
        - in: query
          name: ods-org-role
          description: A role of the organisation
          required: false
          schema:
            type: string
            example: ''
        - in: query
          name: ods-org-primaryRole
          description: Whether a role of the organisation is it's primary role
          required: false
          schema:
            type: string
            example: 'false'
        - in: query
          name: _count
          description: Number of results per page
          required: false
          schema:
            type: string
            example: ''
        - in: query
          name: _summary
          description: just return a count of the matching resources, without returning the actual matches
          required: false
          schema:
            type: string
            example: ''                             
      responses:
        '200':
          description: Valid request that returns organization history found that match the search criteria (which may be 0).
          headers:
            X-Correlation-Id:
              schema:
                type: string
                example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
              description: 'The X-Correlation-ID from the request header, if supplied, mirrored back.'
          content:
            application/fhir+json:
              schema:
                $ref: "immunisation-history-api/specification/components/schemas/bundle.yaml"
              example:
                $ref: "components/examples/read-example.json"



